### PR TITLE
Added examples for summary plot.

### PR DESCRIPTION
**Pull request by azanovivan02**
Changes in this request depend on features of shap library, which were added in pull request: https://github.com/slundberg/shap/pull/1180.

### CODE REVIEW

**Comment by azanovivan02** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

**Comment by ek-ak** [comment]
@arcadia-devtools Ship it!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@arcadia-devtools Ship it!

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by arcadia-devtools** [comment]
CLA already signed

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: [1251327](https://a.yandex-team.ru/review/1251327)

**Pull request merged**
